{
 "title": "OTUS HOMEWORK",
 "description": "Homework for Prometheus & Grafana stack",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(application_by_radchuk_otus_container_GreetingResource_counted_slow_total[1m]))",
     "legendFormat": "/ping/1"
    },
    {
     "expr": "sum(rate(application_by_radchuk_otus_container_GreetingResource_counted_fast_total[1m]))",
     "legendFormat": "/ping/2"
    }
   ]
  },
  {
   "title": "Latency (0.5)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(application_by_radchuk_otus_container_GreetingResource_timed_fast_seconds{quantile=\"0.5\"})",
     "legendFormat": "/ping/1"
    },
    {
     "expr": "avg(application_by_radchuk_otus_container_GreetingResource_timed_slow_seconds{quantile=\"0.5\"})",
     "legendFormat": "/ping/2"
    }
   ]
  },
  {
   "title": "Latency (0.95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(application_by_radchuk_otus_container_GreetingResource_timed_fast_seconds{quantile=\"0.95\"})",
     "legendFormat": "/ping/1"
    },
    {
     "expr": "avg(application_by_radchuk_otus_container_GreetingResource_timed_slow_seconds{quantile=\"0.95\"})",
     "legendFormat": "/ping/2"
    }
   ]
  },
  {
   "title": "RPS (Ingress)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{status=\"200\"}[1m])",
     "legendFormat": "200"
    },
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[1m])",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cpu_systemCpuLoad_percent",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "base_memory_usedHeap_bytes", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}